"""empty message

Revision ID: 621fa124a7e4
Revises: e2581a3d4db5
Create Date: 2016-08-14 22:26:51.469836

"""

# revision identifiers, used by Alembic.
revision = '621fa124a7e4'
down_revision = 'e2581a3d4db5'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('collection',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=True),
    sa.Column('id_book', sa.Integer(), nullable=True),
    sa.Column('quality', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['id_book'], [u'book.id'], ),
    sa.ForeignKeyConstraint(['id_user'], [u'user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('collection')
    ### end Alembic commands ###
