"""empty message

Revision ID: c81d41ca10ca
Revises: cd93a99edee4
Create Date: 2016-07-22 10:57:02.157402

"""

# revision identifiers, used by Alembic.
revision = 'c81d41ca10ca'
down_revision = 'cd93a99edee4'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book', sa.Column('quality', sa.String(), nullable=True))
    op.add_column('book', sa.Column('status', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('book', 'status')
    op.drop_column('book', 'quality')
    ### end Alembic commands ###
